/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.example

import spock.lang.Specification

class TestBowlingScorecard extends Specification {
    def "gutter game has score of 0"() {
        setup:
        def scorecard = new BowlingScorecard()

        when:
        def score = scorecard.score(0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0)

        then:
        score == 0
    }

    def "all 1s game has score of 20"() {
        setup:
        def scorecard = new BowlingScorecard()

        when:
        def score = scorecard.score(1,1, 1,1, 1,1, 1,1, 1,1, 1,1, 1,1, 1,1, 1,1, 1,1)

        then:
        score == 20
    }

    def "spare followed by 1 has score of 12"() {
        setup:
        def scorecard = new BowlingScorecard()

        when:
        def score = scorecard.score(5,5, 1,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0)

        then:
        score == 12
    }

    def "strike followed by 1,1 has score of 14"() {
        setup:
        def scorecard = new BowlingScorecard()

        when:
        def score = scorecard.score(10, 1,1, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0)

        then:
        score == 14
    }

    def "perfect score has score of 300"() {
        setup:
        def scorecard = new BowlingScorecard()

        when:
        def score = scorecard.score(10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10)

        then:
        score == 300
    }
}
