/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import java.util.Arrays;

public class BowlingScorecard {
    public int score(int... scores) {

        int score = 0;

        for(int game = 0, frame = 0; frame < 10; frame++) {
            if(scores[game] == 10) {
                score += 10 + scores[game+1] + scores[game+2];
                game += 1;
            }
            else if(scores[game] + scores[game+1] == 10) {
                score += 10 + scores[game+2];
                game += 2;
            }
            else {
                score += scores[game] + scores[game+1];
                game +=2;
            }
        }

        return score;
    }
}
